### ISSUE TITLE
`updatePsbt` throws an Error when attempting to add another UTXO belonging to the same timelocked descriptor/address

### ISSUE THREAD

**Issue by 0xbrito** [bitcoinerlab/descriptors#15]
This is what will be thrown:
https://github.com/bitcoinerlab/descriptors/blob/48b47b1d6dbd1a1eb5df5f7c3a6abf864637dced/src/psbt.ts#L202-L206

Is this somewhat intended? If `locktime` isn't undefined for the next UTXO it will always trigger the condition above.

https://github.com/bitcoinerlab/descriptors/blob/48b47b1d6dbd1a1eb5df5f7c3a6abf864637dced/src/descriptors.ts#L664

### Possible Solution

Ensure that `psbt.locktime` and `this.getLockTime`  are  not equal before passing a value.

```javascript
// src/descriptors.ts

   ...(psbt.locktime !== this.getLockTime() ? { locktime: this.getLockTime()  } : {}), // <-- L#664
```

And also check for `psbt.locktime` inside `src/psbt.ts`

```javascript
// src/psbt.ts

  if (locktime !== undefined || psbt.locktime !== 0) { // <-- L#210
```

Please, let me know if I'm getting something wrong.

**Comment by landabaso** [comment]
The timelock is set at the tx level. It can only be set once. If the timelock has already been set already then an Error is thrown as a protection. It will throw even when trying to add the same timelock because users may have been unintentionally adding inputs now knowing about this limitation.

I'm not sure how you hit this problem. Did you try adding 2 inputs that require a timelock? Then this is the reason.

**Comment by 0xbrito** [comment]
Yes, agree. That's why I'm suggesting to skip that subsequent `locktime` update if it were already set before.

And yes, I was trying to add 2 inputs that spends from the same descriptor (timelocked) hence they both require timelock.

**Comment by 0xbrito** [comment]
Oh sorry, @landabaso  for late response. I see that you just some changes related to this.
